<a href="https://colab.research.google.com/github/ekacs/Audit-Analytics-Articles/blob/main/R2_ADTT_PANDA_KAPAL_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# spb

In [ ]:
import pandas as pd
import io
import hashlib
from google.colab import files
from IPython.display import display

# Meminta user untuk mengunggah file xls dari inaportnet
print("Silakan unggah file SPB (ext xls) yg diunduh dari Inaportnet:")
uploaded = files.upload()

all_dfs = []

for filename in uploaded.keys():
    try:
        file_bytes = uploaded[filename]
        file_hash = hashlib.sha256(file_bytes).hexdigest()
        print(f"\nReading uploaded file: {filename}")

        dfs = pd.read_html(io.BytesIO(file_bytes))
        if dfs:
            df = dfs[0]
            # Menambahkan kolom source_file
            df['source_file'] = filename
            print(f"Berhasil mengimpor: {filename}")
            all_dfs.append(df)
    except Exception as e:
        try:
            df = pd.read_excel(io.BytesIO(uploaded[filename]), engine='xlrd')
            df['source_file'] = filename
            all_dfs.append(df)
            print(f"Berhasil mengimpor (Excel mode): {filename}")
        except Exception as e2:
            print(f"Gagal membaca {filename}: {e2}")

if all_dfs:
    combined_spb = pd.concat(all_dfs, ignore_index=True)
    print("\nSemua file berhasil digabungkan dengan kolom 'source_file'.")
    display(combined_spb.head(5))
else:
    print("Tidak ada data yang berhasil diimpor.")

Silakan unggah file SPB (ext xls) yg diunduh dari Inaportnet:

Saving SPB.IDLSW.01.2023.xls to SPB.IDLSW.01.2023.xls
Saving SPB.IDLSW.01.2024.xls to SPB.IDLSW.01.2024.xls
Saving SPB.IDLSW.02.2023.xls to SPB.IDLSW.02.2023.xls
Saving SPB.IDLSW.02.2024.xls to SPB.IDLSW.02.2024.xls
Saving SPB.IDLSW.03.2023.xls to SPB.IDLSW.03.2023.xls
Saving SPB.IDLSW.03.2024.xls to SPB.IDLSW.03.2024.xls
Saving SPB.IDLSW.04.2023.xls to SPB.IDLSW.04.2023.xls
Saving SPB.IDLSW.04.2024.xls to SPB.IDLSW.04.2024.xls
Saving SPB.IDLSW.05.2023.xls to SPB.IDLSW.05.2023.xls
Saving SPB.IDLSW.05.2024.xls to SPB.IDLSW.05.2024.xls
Saving SPB.IDLSW.06.2023.xls to SPB.IDLSW.06.2023.xls
Saving SPB.IDLSW.06.2024.xls to SPB.IDLSW.06.2024.xls
Saving SPB.IDLSW.07.2023.xls to SPB.IDLSW.07.2023.xls
Saving SPB.IDLSW.07.2024.xls to SPB.IDLSW.07.2024.xls
Saving SPB.IDLSW.08.2023.xls to SPB.IDLSW.08.2023.xls
Saving SPB.IDLSW.08.2024.xls to SPB.IDLSW.08.2024.xls
Saving SPB.IDLSW.09.2023.xls to SPB.IDLSW.09.2023.xls
Saving SPB.IDLSW.09.2024.xls to SPB.IDLSW.09.2024.xls
Saving SPB.IDLSW.10.2023.xls to SPB.IDLSW.10.2023.xls
Saving SPB.IDLSW.10.2024.xls to SPB.IDLSW.10.2024.xls
Saving SPB.IDLSW.11.2023.xls to SPB.IDLSW.11.2023.xls
Saving SPB.IDLSW.11.2024.xls to SPB.IDLSW.11.2024.xls
Saving SPB.IDLSW.12.2023.xls to SPB.IDLSW.12.2023.xls
Saving SPB.IDLSW.12.2024.xls to SPB.IDLSW.12.2024.xls

Reading uploaded file: SPB.IDLSW.01.2023.xls
Berhasil mengimpor: SPB.IDLSW.01.2023.xls

Reading uploaded file: SPB.IDLSW.01.2024.xls
Berhasil mengimpor: SPB.IDLSW.01.2024.xls

Reading uploaded file: SPB.IDLSW.02.2023.xls
Berhasil mengimpor: SPB.IDLSW.02.2023.xls

Reading uploaded file: SPB.IDLSW.02.2024.xls
Berhasil mengimpor: SPB.IDLSW.02.2024.xls

Reading uploaded file: SPB.IDLSW.03.2023.xls
Berhasil mengimpor: SPB.IDLSW.03.2023.xls

Reading uploaded file: SPB.IDLSW.03.2024.xls
Berhasil mengimpor: SPB.IDLSW.03.2024.xls

Reading uploaded file: SPB.IDLSW.04.2023.xls
Berhasil mengimpor: SPB.IDLSW.04.2023.xls

Reading uploaded file: SPB.IDLSW.04.2024.xls
Berhasil mengimpor: SPB.IDLSW.04.2024.xls

Reading uploaded file: SPB.IDLSW.05.2023.xls
Berhasil mengimpor: SPB.IDLSW.05.2023.xls

Reading uploaded file: SPB.IDLSW.05.2024.xls
Berhasil mengimpor: SPB.IDLSW.05.2024.xls

Reading uploaded file: SPB.IDLSW.06.2023.xls
Berhasil mengimpor: SPB.IDLSW.06.2023.xls

Reading uploaded file: SPB.IDLSW.06.2024.xls
Berhasil mengimpor: SPB.IDLSW.06.2024.xls

Reading uploaded file: SPB.IDLSW.07.2023.xls
Berhasil mengimpor: SPB.IDLSW.07.2023.xls

Reading uploaded file: SPB.IDLSW.07.2024.xls
Berhasil mengimpor: SPB.IDLSW.07.2024.xls

Reading uploaded file: SPB.IDLSW.08.2023.xls
Berhasil mengimpor: SPB.IDLSW.08.2023.xls

Reading uploaded file: SPB.IDLSW.08.2024.xls
Berhasil mengimpor: SPB.IDLSW.08.2024.xls

Reading uploaded file: SPB.IDLSW.09.2023.xls
Berhasil mengimpor: SPB.IDLSW.09.2023.xls

Reading uploaded file: SPB.IDLSW.09.2024.xls
Berhasil mengimpor: SPB.IDLSW.09.2024.xls

Reading uploaded file: SPB.IDLSW.10.2023.xls
Berhasil mengimpor: SPB.IDLSW.10.2023.xls

Reading uploaded file: SPB.IDLSW.10.2024.xls
Berhasil mengimpor: SPB.IDLSW.10.2024.xls

Reading uploaded file: SPB.IDLSW.11.2023.xls
Berhasil mengimpor: SPB.IDLSW.11.2023.xls

Reading uploaded file: SPB.IDLSW.11.2024.xls
Berhasil mengimpor: SPB.IDLSW.11.2024.xls

Reading uploaded file: SPB.IDLSW.12.2023.xls
Berhasil mengimpor: SPB.IDLSW.12.2023.xls

Reading uploaded file: SPB.IDLSW.12.2024.xls
Berhasil mengimpor: SPB.IDLSW.12.2024.xls

Semua file berhasil digabungkan dengan kolom 'source_file'.

,No,Agen,Kapal,Tipe Kapal,PKK,SPB,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Tanggal Tiba,Tanggal Terbit,Tanggal Tolak,Billing Labuh,NTPN Labuh,Billing Rambu,NTPN Rambu,Petugas,No SPK,source_file
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,2022-12-31 06:00:00,2023-01-01 13:07:18,2023-01-01 16:00:00,'820230101616447,195796U8EKQK9HPV,'820230101617327,9B1846U8EKQK9ILF,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0001,SPB.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,2022-12-29 10:30:00,2023-01-01 13:07:30,2023-01-01 21:00:00,'820230101615572,70F0B2G4VFUM8GUK,'820230101617328,565E27QLUFD0MILG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,2023-01-01 02:00:00,2023-01-01 19:36:54,2023-01-02 07:00:00,'820230101626188,F9EFD7QLUFD0MRAC,'820230101623368,FA6377QLUFD0MOI8,"YUSRIADI, A. Md",IDLSW-202517530825,SPB.IDLSW.01.2023.xls
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,2023-01-02 05:00:00,2023-01-02 14:59:01,2023-01-03 08:00:00,'820230102691095,C05CE55DEVLSGB8N,'820230102665872,4F31C2G4VFUN8IKG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,2022-12-31 17:45:00,2023-01-02 15:56:43,2023-01-02 21:00:00,'820230102691071,8A84E1JNFLCASB7V,'820230102681149,41E708N3E9VE41HT,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0002,SPB.IDLSW.01.2023.xls

In [ ]:
print(f"Jumlah baris sebelum penghapusan duplikat: {len(combined_spb)}")

duplicate_rows = combined_spb.duplicated().sum()

if duplicate_rows > 0:
    print(f"Ditemukan {duplicate_rows} baris duplikat di combined_spb. Membersihkan...")
    combined_spb = combined_spb.drop_duplicates(keep='first')
    print(f"Jumlah baris setelah penghapusan duplikat: {len(combined_spb)}")
    print("Duplikat berhasil dihapus.")
else:
    print("Tidak ditemukan baris duplikat di combined_spb.")

display(combined_spb.head())

Jumlah baris sebelum penghapusan duplikat: 1667
Tidak ditemukan baris duplikat di combined_spb.

,No,Agen,Kapal,Tipe Kapal,PKK,SPB,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Tanggal Tiba,Tanggal Terbit,Tanggal Tolak,Billing Labuh,NTPN Labuh,Billing Rambu,NTPN Rambu,Petugas,No SPK,source_file
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,2022-12-31 06:00:00,2023-01-01 13:07:18,2023-01-01 16:00:00,'820230101616447,195796U8EKQK9HPV,'820230101617327,9B1846U8EKQK9ILF,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0001,SPB.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,2022-12-29 10:30:00,2023-01-01 13:07:30,2023-01-01 21:00:00,'820230101615572,70F0B2G4VFUM8GUK,'820230101617328,565E27QLUFD0MILG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,2023-01-01 02:00:00,2023-01-01 19:36:54,2023-01-02 07:00:00,'820230101626188,F9EFD7QLUFD0MRAC,'820230101623368,FA6377QLUFD0MOI8,"YUSRIADI, A. Md",IDLSW-202517530825,SPB.IDLSW.01.2023.xls
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,2023-01-02 05:00:00,2023-01-02 14:59:01,2023-01-03 08:00:00,'820230102691095,C05CE55DEVLSGB8N,'820230102665872,4F31C2G4VFUN8IKG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,2022-12-31 17:45:00,2023-01-02 15:56:43,2023-01-02 21:00:00,'820230102691071,8A84E1JNFLCASB7V,'820230102681149,41E708N3E9VE41HT,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0002,SPB.IDLSW.01.2023.xls

In [ ]:
display(combined_spb.tail(5))

In [ ]:
import pandas as pd

# 1. Merubah kolom 'No' menjadi string
combined_spb['No'] = combined_spb['No'].astype(str)

# 2. Merubah kolom tanggal menjadi datetime
# Format standar pandas to_datetime biasanya otomatis mendeteksi format yang ada
# errors='coerce' digunakan agar data yang tidak valid berubah menjadi NaT (Not a Time)
date_columns = ['Tanggal Tiba', 'Tanggal Terbit', 'Tanggal Tolak']

for col in date_columns:
    combined_spb[col] = pd.to_datetime(combined_spb[col], errors='coerce')

# Verifikasi perubahan tipe data
print("Tipe data kolom setelah perubahan:")
print(combined_spb[['No', 'Tanggal Tiba', 'Tanggal Terbit', 'Tanggal Tolak']].dtypes)
display(combined_spb.head())

Tipe data kolom setelah perubahan:
No                        object
Tanggal Tiba      datetime64[ns]
Tanggal Terbit    datetime64[ns]
Tanggal Tolak     datetime64[ns]
dtype: object

,No,Agen,Kapal,Tipe Kapal,PKK,SPB,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Tanggal Tiba,Tanggal Terbit,Tanggal Tolak,Billing Labuh,NTPN Labuh,Billing Rambu,NTPN Rambu,Petugas,No SPK,source_file
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,2022-12-31 06:00:00,2023-01-01 13:07:18,2023-01-01 16:00:00,'820230101616447,195796U8EKQK9HPV,'820230101617327,9B1846U8EKQK9ILF,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0001,SPB.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,2022-12-29 10:30:00,2023-01-01 13:07:30,2023-01-01 21:00:00,'820230101615572,70F0B2G4VFUM8GUK,'820230101617328,565E27QLUFD0MILG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,2023-01-01 02:00:00,2023-01-01 19:36:54,2023-01-02 07:00:00,'820230101626188,F9EFD7QLUFD0MRAC,'820230101623368,FA6377QLUFD0MOI8,"YUSRIADI, A. Md",IDLSW-202517530825,SPB.IDLSW.01.2023.xls
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,2023-01-02 05:00:00,2023-01-02 14:59:01,2023-01-03 08:00:00,'820230102691095,C05CE55DEVLSGB8N,'820230102665872,4F31C2G4VFUN8IKG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,2022-12-31 17:45:00,2023-01-02 15:56:43,2023-01-02 21:00:00,'820230102691071,8A84E1JNFLCASB7V,'820230102681149,41E708N3E9VE41HT,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0002,SPB.IDLSW.01.2023.xls

In [ ]:
print(combined_spb.info()) #dataframe_SPB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1667 entries, 0 to 1666
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   No                       1667 non-null   object
 1   Agen                     1667 non-null   object
 2   Kapal                    1667 non-null   object
 3   Tipe Kapal               1667 non-null   object
 4   PKK                      1667 non-null   object
 5   SPB                      1667 non-null   object
 6   Nakhoda                  1654 non-null   object
 7   Bendera                  1667 non-null   object
 8   IMO                      1482 non-null   object
 9   Tanda Pendaftaran Kapal  1667 non-null   object
 10  Call Sign                1655 non-null   object
 11  GT                       1667 non-null   int64
 12  LOA                      1666 non-null   float64
 13  Jumlah Awak              1667 non-null   int64
 14  Muatan                   1667 non-null   object
 15  Pelabuhan Asal           1667 non-null   object
 16  Pelabuhan Tujuan         1667 non-null   object
 17  Posisi Tolak             1667 non-null   object
 18  Tanggal Tiba             1667 non-null   datetime64[ns]
 19  Tanggal Terbit           1667 non-null   datetime64[ns]
 20  Tanggal Tolak            1667 non-null   datetime64[ns]
 21  Billing Labuh            1667 non-null   object
 22  NTPN Labuh               1664 non-null   object
 23  Billing Rambu            1667 non-null   object
 24  NTPN Rambu               1665 non-null   object
 25  Petugas                  1667 non-null   object
 26  No SPK                   1526 non-null   object
 27  source_file              1667 non-null   object
dtypes: datetime64[ns](3), float64(1), int64(2), object(22)
memory usage: 364.8+ KB
None

In [ ]:
from google.colab import files

# Mendefinisikan nama file
output_filename = 'combined_spb.xlsx'

# Ekspor dataframe ke Excel
combined_spb.to_excel(output_filename, index=False)

# Mengunduh file ke komputer lokal
files.download(output_filename)

print(f"Dataframe berhasil diekspor ke {output_filename} dan proses unduhan dimulai.")

Dataframe berhasil diekspor ke combined_spb.xlsx dan proses unduhan dimulai.

#spog

In [ ]:
import pandas as pd
import io
import hashlib
from google.colab import files
from IPython.display import display

# Meminta user untuk mengunggah file xls dari inaportnet
print("Silakan unggah file SPOG (ext xls) yg diunduh dari Inapornet:")
uploaded = files.upload()

all_dfs = []

for filename in uploaded.keys():
    try:
        file_bytes = uploaded[filename]
        file_hash = hashlib.sha256(file_bytes).hexdigest()
        print(f"\nReading uploaded file: {filename}")

        dfs = pd.read_html(io.BytesIO(file_bytes))
        if dfs:
            df = dfs[0]
            # Menambahkan kolom source_file
            df['source_file'] = filename
            print(f"Berhasil mengimpor: {filename}")
            all_dfs.append(df)
    except Exception as e:
        try:
            df = pd.read_excel(io.BytesIO(uploaded[filename]), engine='xlrd')
            df['source_file'] = filename
            all_dfs.append(df)
            print(f"Berhasil mengimpor (Excel mode): {filename}")
        except Exception as e2:
            print(f"Gagal membaca {filename}: {e2}")

if all_dfs:
    combined_spog = pd.concat(all_dfs, ignore_index=True)
    print("\nSemua file berhasil digabungkan dengan kolom 'source_file'.")
    display(combined_spog.head(5))
else:
    print("Tidak ada data yang berhasil diimpor.")

Silakan unggah file SPOG (ext xls) yg diunduh dari Inapornet:

Saving SPOG.IDLSW.01.2023.xls to SPOG.IDLSW.01.2023.xls
Saving SPOG.IDLSW.01.2024.xls to SPOG.IDLSW.01.2024.xls
Saving SPOG.IDLSW.02.2023.xls to SPOG.IDLSW.02.2023.xls
Saving SPOG.IDLSW.02.2024.xls to SPOG.IDLSW.02.2024.xls
Saving SPOG.IDLSW.03.2023.xls to SPOG.IDLSW.03.2023.xls
Saving SPOG.IDLSW.03.2024.xls to SPOG.IDLSW.03.2024.xls
Saving SPOG.IDLSW.04.2023.xls to SPOG.IDLSW.04.2023.xls
Saving SPOG.IDLSW.04.2024.xls to SPOG.IDLSW.04.2024.xls
Saving SPOG.IDLSW.05.2023.xls to SPOG.IDLSW.05.2023.xls
Saving SPOG.IDLSW.05.2024.xls to SPOG.IDLSW.05.2024.xls
Saving SPOG.IDLSW.06.2023.xls to SPOG.IDLSW.06.2023.xls
Saving SPOG.IDLSW.06.2024.xls to SPOG.IDLSW.06.2024.xls
Saving SPOG.IDLSW.07.2023.xls to SPOG.IDLSW.07.2023.xls
Saving SPOG.IDLSW.07.2024.xls to SPOG.IDLSW.07.2024.xls
Saving SPOG.IDLSW.08.2023.xls to SPOG.IDLSW.08.2023.xls
Saving SPOG.IDLSW.08.2024.xls to SPOG.IDLSW.08.2024.xls
Saving SPOG.IDLSW.09.2023.xls to SPOG.IDLSW.09.2023.xls
Saving SPOG.IDLSW.09.2024.xls to SPOG.IDLSW.09.2024.xls
Saving SPOG.IDLSW.10.2023.xls to SPOG.IDLSW.10.2023.xls
Saving SPOG.IDLSW.10.2024.xls to SPOG.IDLSW.10.2024.xls
Saving SPOG.IDLSW.11.2023.xls to SPOG.IDLSW.11.2023.xls
Saving SPOG.IDLSW.11.2024.xls to SPOG.IDLSW.11.2024.xls
Saving SPOG.IDLSW.12.2023.xls to SPOG.IDLSW.12.2023.xls
Saving SPOG.IDLSW.12.2024.xls to SPOG.IDLSW.12.2024.xls

Reading uploaded file: SPOG.IDLSW.01.2023.xls
Berhasil mengimpor: SPOG.IDLSW.01.2023.xls

Reading uploaded file: SPOG.IDLSW.01.2024.xls
Berhasil mengimpor: SPOG.IDLSW.01.2024.xls

Reading uploaded file: SPOG.IDLSW.02.2023.xls
Berhasil mengimpor: SPOG.IDLSW.02.2023.xls

Reading uploaded file: SPOG.IDLSW.02.2024.xls
Berhasil mengimpor: SPOG.IDLSW.02.2024.xls

Reading uploaded file: SPOG.IDLSW.03.2023.xls
Berhasil mengimpor: SPOG.IDLSW.03.2023.xls

Reading uploaded file: SPOG.IDLSW.03.2024.xls
Berhasil mengimpor: SPOG.IDLSW.03.2024.xls

Reading uploaded file: SPOG.IDLSW.04.2023.xls
Berhasil mengimpor: SPOG.IDLSW.04.2023.xls

Reading uploaded file: SPOG.IDLSW.04.2024.xls
Berhasil mengimpor: SPOG.IDLSW.04.2024.xls

Reading uploaded file: SPOG.IDLSW.05.2023.xls
Berhasil mengimpor: SPOG.IDLSW.05.2023.xls

Reading uploaded file: SPOG.IDLSW.05.2024.xls
Berhasil mengimpor: SPOG.IDLSW.05.2024.xls

Reading uploaded file: SPOG.IDLSW.06.2023.xls
Berhasil mengimpor: SPOG.IDLSW.06.2023.xls

Reading uploaded file: SPOG.IDLSW.06.2024.xls
Berhasil mengimpor: SPOG.IDLSW.06.2024.xls

Reading uploaded file: SPOG.IDLSW.07.2023.xls
Berhasil mengimpor: SPOG.IDLSW.07.2023.xls

Reading uploaded file: SPOG.IDLSW.07.2024.xls
Berhasil mengimpor: SPOG.IDLSW.07.2024.xls

Reading uploaded file: SPOG.IDLSW.08.2023.xls
Berhasil mengimpor: SPOG.IDLSW.08.2023.xls

Reading uploaded file: SPOG.IDLSW.08.2024.xls
Berhasil mengimpor: SPOG.IDLSW.08.2024.xls

Reading uploaded file: SPOG.IDLSW.09.2023.xls
Berhasil mengimpor: SPOG.IDLSW.09.2023.xls

Reading uploaded file: SPOG.IDLSW.09.2024.xls
Berhasil mengimpor: SPOG.IDLSW.09.2024.xls

Reading uploaded file: SPOG.IDLSW.10.2023.xls
Berhasil mengimpor: SPOG.IDLSW.10.2023.xls

Reading uploaded file: SPOG.IDLSW.10.2024.xls
Berhasil mengimpor: SPOG.IDLSW.10.2024.xls

Reading uploaded file: SPOG.IDLSW.11.2023.xls
Berhasil mengimpor: SPOG.IDLSW.11.2023.xls

Reading uploaded file: SPOG.IDLSW.11.2024.xls
Berhasil mengimpor: SPOG.IDLSW.11.2024.xls

Reading uploaded file: SPOG.IDLSW.12.2023.xls
Berhasil mengimpor: SPOG.IDLSW.12.2023.xls

Reading uploaded file: SPOG.IDLSW.12.2024.xls
Berhasil mengimpor: SPOG.IDLSW.12.2024.xls

Semua file berhasil digabungkan dengan kolom 'source_file'.

,No,Agen,Kapal,Tipe Kapal,PKK,No SPOG,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,GT,LOA,Dari,Ke,Tujuan,Pandu,SPK,Petugas,Waktu Gerak,source_file
0,1,PT. PELAYARAN SEA ASIH LINES,BERAU MAS,GENERAL CARGO,PKK.DN.IDLSW.2212.000068,SPOG.IDLSW.0123.0000001,Candi Eka,ID,0.0,2011 Ba No. 2595/L,...,2003,85.95,LAUT,PELINDO - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202509352725,"YUSRIADI, A. Md",2023-01-01 11:11:00,SPOG.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPOG.IDLSW.0123.0000002,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,1951,67.80,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,Capt Tengku Radiansyahputra,IDLSW-SPK-2212-000-0028,"YUSRIADI, A. Md",2022-12-31 19:00:00,SPOG.IDLSW.01.2023.xls
2,3,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPOG.IDLSW.0123.0000003,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,13688,102.20,LAUT,Area Labuh Kapal General Cargo,labuh,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 08:00:00,SPOG.IDLSW.01.2023.xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,AEROSEA CATALINA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2301.000001,SPOG.IDLSW.0123.0000004,SUMARIANTO,ID,9554913.0,2021 Pst No. 929/L,...,5153,99.99,LAUT,TUKS PERTAMINA - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202611153426,"YUSRIADI, A. Md",2023-01-03 07:00:00,SPOG.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2301.000003,SPOG.IDLSW.0123.0000005,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,161,35.15,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 11:00:00,SPOG.IDLSW.01.2023.xls

In [ ]:
print(f"Jumlah baris sebelum penghapusan duplikat: {len(combined_spog)}")

duplicate_rows = combined_spog.duplicated().sum()

if duplicate_rows > 0:
    print(f"Ditemukan {duplicate_rows} baris duplikat di combined_spog. Membersihkan...")
    combined_spog = combined_spog.drop_duplicates(keep='first')
    print(f"Jumlah baris setelah penghapusan duplikat: {len(combined_spog)}")
    print("Duplikat berhasil dihapus.")
else:
    print("Tidak ditemukan baris duplikat di combined_spog.")

display(combined_spog.head())

Jumlah baris sebelum penghapusan duplikat: 1903
Tidak ditemukan baris duplikat di combined_spog.

,No,Agen,Kapal,Tipe Kapal,PKK,No SPOG,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,GT,LOA,Dari,Ke,Tujuan,Pandu,SPK,Petugas,Waktu Gerak,source_file
0,1,PT. PELAYARAN SEA ASIH LINES,BERAU MAS,GENERAL CARGO,PKK.DN.IDLSW.2212.000068,SPOG.IDLSW.0123.0000001,Candi Eka,ID,0.0,2011 Ba No. 2595/L,...,2003,85.95,LAUT,PELINDO - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202509352725,"YUSRIADI, A. Md",2023-01-01 11:11:00,SPOG.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPOG.IDLSW.0123.0000002,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,1951,67.80,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,Capt Tengku Radiansyahputra,IDLSW-SPK-2212-000-0028,"YUSRIADI, A. Md",2022-12-31 19:00:00,SPOG.IDLSW.01.2023.xls
2,3,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPOG.IDLSW.0123.0000003,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,13688,102.20,LAUT,Area Labuh Kapal General Cargo,labuh,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 08:00:00,SPOG.IDLSW.01.2023.xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,AEROSEA CATALINA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2301.000001,SPOG.IDLSW.0123.0000004,SUMARIANTO,ID,9554913.0,2021 Pst No. 929/L,...,5153,99.99,LAUT,TUKS PERTAMINA - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202611153426,"YUSRIADI, A. Md",2023-01-03 07:00:00,SPOG.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2301.000003,SPOG.IDLSW.0123.0000005,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,161,35.15,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 11:00:00,SPOG.IDLSW.01.2023.xls

In [ ]:
# 1. Merubah kolom 'No' menjadi string
combined_spog['No'] = combined_spog['No'].astype(str)

# 2. Merubah kolom 'Waktu Gerak' menjadi datetime
# Format data: yyyy-mm-dd hh:mm:ss
combined_spog['Waktu Gerak'] = pd.to_datetime(combined_spog['Waktu Gerak'], errors='coerce')

# Verifikasi perubahan tipe data
print("Tipe data kolom setelah perubahan:")
print(combined_spog[['No', 'Waktu Gerak']].dtypes)
display(combined_spog.head())

Tipe data kolom setelah perubahan:
No                     object
Waktu Gerak    datetime64[ns]
dtype: object

,No,Agen,Kapal,Tipe Kapal,PKK,No SPOG,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,GT,LOA,Dari,Ke,Tujuan,Pandu,SPK,Petugas,Waktu Gerak,source_file
0,1,PT. PELAYARAN SEA ASIH LINES,BERAU MAS,GENERAL CARGO,PKK.DN.IDLSW.2212.000068,SPOG.IDLSW.0123.0000001,Candi Eka,ID,0.0,2011 Ba No. 2595/L,...,2003,85.95,LAUT,PELINDO - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202509352725,"YUSRIADI, A. Md",2023-01-01 11:11:00,SPOG.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPOG.IDLSW.0123.0000002,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,1951,67.80,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,Capt Tengku Radiansyahputra,IDLSW-SPK-2212-000-0028,"YUSRIADI, A. Md",2022-12-31 19:00:00,SPOG.IDLSW.01.2023.xls
2,3,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPOG.IDLSW.0123.0000003,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,13688,102.20,LAUT,Area Labuh Kapal General Cargo,labuh,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 08:00:00,SPOG.IDLSW.01.2023.xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,AEROSEA CATALINA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2301.000001,SPOG.IDLSW.0123.0000004,SUMARIANTO,ID,9554913.0,2021 Pst No. 929/L,...,5153,99.99,LAUT,TUKS PERTAMINA - MULTIPURPOSE,Masuk,MUHAMMAD NURDIANSYAH,IDLSW-202611153426,"YUSRIADI, A. Md",2023-01-03 07:00:00,SPOG.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2301.000003,SPOG.IDLSW.0123.0000005,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,161,35.15,LAUT,TUKS PAG - DERMAGA II (MARGINAL),Masuk,NaN,NaN,"YUSRIADI, A. Md",2023-01-02 11:00:00,SPOG.IDLSW.01.2023.xls

In [ ]:
print(combined_spog.info()) #dataframe_spog

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1903 entries, 0 to 1902
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   No                       1903 non-null   object
 1   Agen                     1903 non-null   object
 2   Kapal                    1903 non-null   object
 3   Tipe Kapal               1903 non-null   object
 4   PKK                      1903 non-null   object
 5   No SPOG                  1903 non-null   object
 6   Nakhoda                  1878 non-null   object
 7   Bendera                  1903 non-null   object
 8   IMO                      1660 non-null   object
 9   Tanda Pendaftaran Kapal  1903 non-null   object
 10  Call Sign                1879 non-null   object
 11  GT                       1903 non-null   int64
 12  LOA                      1902 non-null   float64
 13  Dari                     1903 non-null   object
 14  Ke                       1903 non-null   object
 15  Tujuan                   1903 non-null   object
 16  Pandu                    1715 non-null   object
 17  SPK                      1715 non-null   object
 18  Petugas                  1903 non-null   object
 19  Waktu Gerak              1903 non-null   datetime64[ns]
 20  source_file              1903 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(18)
memory usage: 312.3+ KB
None

In [ ]:
#ekspor dataframe ke excell

from google.colab import files

# Mendefinisikan nama file
output_filename = 'combined_spog.xlsx'

# Ekspor dataframe ke Excel
combined_spog.to_excel(output_filename, index=False)

# Mengunduh file ke komputer lokal
files.download(output_filename)

print(f"Dataframe berhasil diekspor ke {output_filename} dan proses unduhan dimulai.")

Dataframe berhasil diekspor ke combined_spog.xlsx dan proses unduhan dimulai.

# rkbm

In [ ]:
import pandas as pd
import io
import hashlib
from google.colab import files
from IPython.display import display

# Meminta user untuk mengunggah file xls dari inaportnet
print("Silakan unggah file RKBM (ext xls) yg diunduh dari Inapornet:")
uploaded = files.upload()

all_dfs = []

for filename in uploaded.keys():
    try:
        file_bytes = uploaded[filename]
        file_hash = hashlib.sha256(file_bytes).hexdigest()
        print(f"\nReading uploaded file: {filename}")

        dfs = pd.read_html(io.BytesIO(file_bytes))
        if dfs:
            df = dfs[0]
            # Menambahkan kolom source_file
            df['source_file'] = filename
            print(f"Berhasil mengimpor: {filename}")
            all_dfs.append(df)
    except Exception as e:
        try:
            df = pd.read_excel(io.BytesIO(uploaded[filename]), engine='xlrd')
            df['source_file'] = filename
            all_dfs.append(df)
            print(f"Berhasil mengimpor (Excel mode): {filename}")
        except Exception as e2:
            print(f"Gagal membaca {filename}: {e2}")

if all_dfs:
    combined_rkbm = pd.concat(all_dfs, ignore_index=True)
    print("\nSemua file berhasil digabungkan dengan kolom 'source_file'.")
    display(combined_rkbm.head(5))
else:
    print("Tidak ada data yang berhasil diimpor.")

Silakan unggah file RKBM (ext xls) yg diunduh dari Inapornet:

Saving RKBM.IDLSW.2023-01-01.xls to RKBM.IDLSW.2023-01-01.xls
Saving RKBM.IDLSW.2024-01-01.xls to RKBM.IDLSW.2024-01-01.xls

Reading uploaded file: RKBM.IDLSW.2023-01-01.xls
Berhasil mengimpor: RKBM.IDLSW.2023-01-01.xls

Reading uploaded file: RKBM.IDLSW.2024-01-01.xls
Berhasil mengimpor: RKBM.IDLSW.2024-01-01.xls

Semua file berhasil digabungkan dengan kolom 'source_file'.

  No               NOMOR RKBM                 NOMOR PKK  \
  No               NOMOR RKBM                 NOMOR PKK
0  1  SL004.IDLSW.0423.000001  PKK.LN.IDLSW.2303.000067
1  2  SL004.IDLSW.0823.000034  PKK.DN.IDLSW.2308.000040
2  3  SL004.IDLSW.0223.000017  PKK.LN.IDLSW.2302.000019
3  4  SL004.IDLSW.0323.000051  PKK.LN.IDLSW.2303.000064
4  5  SL004.IDLSW.0123.000006  PKK.DN.IDLSW.2301.000014

                                PBM                       Lokasi  \
                                PBM                       Lokasi
0              INTAN ACEH DEWANTARA    DERMAGA I (JETTY DOPLHIN)
1       PT. VISINDO JASATAMA SUKSES    DERMAGA I (JETTY DOPLHIN)
2    PT. PELAYARAN BAHTERA ADHIGUNA           DERMAGA II (JETTY)
3              INTAN ACEH DEWANTARA  DERMAGA III (JETTY DOPLHIN)
4  PT PELABUHAN INDONESIA (PERSERO)       PELINDO - MULTIPURPOSE

                                  AGEN            KAPAL           JENIS KAPAL  \
                                  AGEN            KAPAL           JENIS KAPAL
0  PT. PELAYARAN FAJAR SRIBAHARI SAKTI   MV. LMZ EUROPA  BULK CARRIER / CURAH
1               PT. SANINDO ANTAR NUSA  PUSRI INDONESIA         GENERAL CARGO
2       PT. PELAYARAN BAHTERA ADHIGUNA     GAS CRUSADER  BULK CARRIER / CURAH
3  PT. PELAYARAN FAJAR SRIBAHARI SAKTI   MV. LMZ EUROPA  BULK CARRIER / CURAH
4         PT. PELAYARAN SEA ASIH LINES        BERAU MAS         GENERAL CARGO

  BENDERA UKURAN  ...        MUAT                                         \
  BENDERA    DWT  ...     SELESAI SISTEM          KOMODITI         JENIS
0      MH  56771  ...         NaN      -                 -             -
1      ID      0  ...  2023-08-31     TL  PUPUK UREA CURAH  Curah Kering
2      MY   2284  ...  2023-02-13      P            AMONIA    Curah Cair
3      MH  56771  ...         NaN      -                 -             -
4      ID      0  ...  2023-01-06      -                 -             -

                            TGL APPROVE           PETUGAS  \
    TON UNIT    M3          TGL APPROVE           PETUGAS
0     -    -     -  2023-04-01 10:12:14  MAULIDA ADNI, SE
1  8000    1   800  2023-08-24 16:04:21  MAULIDA ADNI, SE
2  1300    1  1300  2023-02-09 16:32:24  MAULIDA ADNI, SE
3     -    -     -  2023-03-31 10:01:35  MAULIDA ADNI, SE
4     -    -     -  2023-01-05 13:05:01  MAULIDA ADNI, SE

                 source_file

0  RKBM.IDLSW.2023-01-01.xls
1  RKBM.IDLSW.2023-01-01.xls
2  RKBM.IDLSW.2023-01-01.xls
3  RKBM.IDLSW.2023-01-01.xls
4  RKBM.IDLSW.2023-01-01.xls

[5 rows x 31 columns]

In [ ]:
# Memeriksa apakah terdapat MultiIndex pada kolom
if isinstance(combined_rkbm.columns, pd.MultiIndex):
    print("Multi-index terdeteksi. Melakukan perbaikan...")

    # Menggabungkan level index menjadi satu nama string
    # Jika level kedua adalah string kosong atau sama dengan level pertama, kita bisa merapikannya
    new_columns = []
    for col in combined_rkbm.columns:
        # Membersihkan nama jika level 0 dan level 1 sama atau level 1 kosong
        if col[1] == "" or col[0] == col[1]:
            new_columns.append(col[0])
        else:
            new_columns.append(f"{col[0]}_{col[1]}")

    combined_rkbm.columns = new_columns
    print("Header telah diperbaiki menjadi single-index.")
else:
    print("Dataframe tidak menggunakan MultiIndex.")

# Menampilkan info dan preview hasil
print("\nInfo Kolom Baru:")
print(combined_rkbm.columns.tolist())
display(combined_rkbm.head())

Multi-index terdeteksi. Melakukan perbaikan...
Header telah diperbaiki menjadi single-index.

Info Kolom Baru:
['No', 'NOMOR RKBM', 'NOMOR PKK', 'PBM', 'Lokasi', 'AGEN', 'KAPAL', 'JENIS KAPAL', 'BENDERA', 'UKURAN_DWT', 'UKURAN_GT', 'UKURAN_LOA', 'BONGKAR_MULAI', 'BONGKAR_SELESAI', 'BONGKAR_SISTEM', 'BONGKAR_KOMODITI', 'BONGKAR_JENIS', 'BONGKAR_TON', 'BONGKAR_UNIT', 'BONGKAR_M3', 'MUAT_MULAI', 'MUAT_SELESAI', 'MUAT_SISTEM', 'MUAT_KOMODITI', 'MUAT_JENIS', 'MUAT_TON', 'MUAT_UNIT', 'MUAT_M3', 'TGL APPROVE', 'PETUGAS', 'source_file']

,No,NOMOR RKBM,NOMOR PKK,PBM,Lokasi,AGEN,KAPAL,JENIS KAPAL,BENDERA,UKURAN_DWT,...,MUAT_SELESAI,MUAT_SISTEM,MUAT_KOMODITI,MUAT_JENIS,MUAT_TON,MUAT_UNIT,MUAT_M3,TGL APPROVE,PETUGAS,source_file
0,1,SL004.IDLSW.0423.000001,PKK.LN.IDLSW.2303.000067,INTAN ACEH DEWANTARA,DERMAGA I (JETTY DOPLHIN),PT. PELAYARAN FAJAR SRIBAHARI SAKTI,MV. LMZ EUROPA,BULK CARRIER / CURAH,MH,56771,...,NaN,-,-,-,-,-,-,2023-04-01 10:12:14,"MAULIDA ADNI, SE",RKBM.IDLSW.2023-01-01.xls
1,2,SL004.IDLSW.0823.000034,PKK.DN.IDLSW.2308.000040,PT. VISINDO JASATAMA SUKSES,DERMAGA I (JETTY DOPLHIN),PT. SANINDO ANTAR NUSA,PUSRI INDONESIA,GENERAL CARGO,ID,0,...,2023-08-31,TL,PUPUK UREA CURAH,Curah Kering,8000,1,800,2023-08-24 16:04:21,"MAULIDA ADNI, SE",RKBM.IDLSW.2023-01-01.xls
2,3,SL004.IDLSW.0223.000017,PKK.LN.IDLSW.2302.000019,PT. PELAYARAN BAHTERA ADHIGUNA,DERMAGA II (JETTY),PT. PELAYARAN BAHTERA ADHIGUNA,GAS CRUSADER,BULK CARRIER / CURAH,MY,2284,...,2023-02-13,P,AMONIA,Curah Cair,1300,1,1300,2023-02-09 16:32:24,"MAULIDA ADNI, SE",RKBM.IDLSW.2023-01-01.xls
3,4,SL004.IDLSW.0323.000051,PKK.LN.IDLSW.2303.000064,INTAN ACEH DEWANTARA,DERMAGA III (JETTY DOPLHIN),PT. PELAYARAN FAJAR SRIBAHARI SAKTI,MV. LMZ EUROPA,BULK CARRIER / CURAH,MH,56771,...,NaN,-,-,-,-,-,-,2023-03-31 10:01:35,"MAULIDA ADNI, SE",RKBM.IDLSW.2023-01-01.xls
4,5,SL004.IDLSW.0123.000006,PKK.DN.IDLSW.2301.000014,PT PELABUHAN INDONESIA (PERSERO),PELINDO - MULTIPURPOSE,PT. PELAYARAN SEA ASIH LINES,BERAU MAS,GENERAL CARGO,ID,0,...,2023-01-06,-,-,-,-,-,-,2023-01-05 13:05:01,"MAULIDA ADNI, SE",RKBM.IDLSW.2023-01-01.xls

In [ ]:
print(f"Jumlah baris sebelum penghapusan duplikat: {len(combined_rkbm)}")

duplicate_rows = combined_rkbm.duplicated().sum()

if duplicate_rows > 0:
    print(f"Ditemukan {duplicate_rows} baris duplikat di combined_rkbm. Membersihkan...")
    combined_rkbm = combined_rkbm.drop_duplicates(keep='first')
    print(f"Jumlah baris setelah penghapusan duplikat: {len(combined_rkbm)}")
    print("Duplikat berhasil dihapus.")
else:
    print("Tidak ditemukan baris duplikat di combined_rkbm.")

display(combined_spb.head())

Jumlah baris sebelum penghapusan duplikat: 1437
Tidak ditemukan baris duplikat di combined_rkbm.

,No,Agen,Kapal,Tipe Kapal,PKK,SPB,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Tanggal Tiba,Tanggal Terbit,Tanggal Tolak,Billing Labuh,NTPN Labuh,Billing Rambu,NTPN Rambu,Petugas,No SPK,source_file
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,2022-12-31 06:00:00,2023-01-01 13:07:18,2023-01-01 16:00:00,'820230101616447,195796U8EKQK9HPV,'820230101617327,9B1846U8EKQK9ILF,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0001,SPB.IDLSW.01.2023.xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,2022-12-29 10:30:00,2023-01-01 13:07:30,2023-01-01 21:00:00,'820230101615572,70F0B2G4VFUM8GUK,'820230101617328,565E27QLUFD0MILG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,2023-01-01 02:00:00,2023-01-01 19:36:54,2023-01-02 07:00:00,'820230101626188,F9EFD7QLUFD0MRAC,'820230101623368,FA6377QLUFD0MOI8,"YUSRIADI, A. Md",IDLSW-202517530825,SPB.IDLSW.01.2023.xls
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,2023-01-02 05:00:00,2023-01-02 14:59:01,2023-01-03 08:00:00,'820230102691095,C05CE55DEVLSGB8N,'820230102665872,4F31C2G4VFUN8IKG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,2022-12-31 17:45:00,2023-01-02 15:56:43,2023-01-02 21:00:00,'820230102691071,8A84E1JNFLCASB7V,'820230102681149,41E708N3E9VE41HT,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0002,SPB.IDLSW.01.2023.xls

In [ ]:
# 1. Merubah kolom 'No' menjadi string
combined_rkbm['No'] = combined_rkbm['No'].astype(str)

# 2. Merubah kolom tanggal bongkar muat menjadi format datetime (yyyy-mm-dd)
date_cols = ['BONGKAR_MULAI', 'BONGKAR_SELESAI', 'MUAT_MULAI', 'MUAT_SELESAI']
for col in date_cols:
    combined_rkbm[col] = pd.to_datetime(combined_rkbm[col], errors='coerce')

# 3. Merubah kolom TGL APPROVE menjadi datetime
combined_rkbm['TGL APPROVE'] = pd.to_datetime(combined_rkbm['TGL APPROVE'], errors='coerce')

# Verifikasi hasil
print("Tipe data kolom setelah standarisasi:")
print(combined_rkbm[['BONGKAR_MULAI', 'BONGKAR_SELESAI', 'MUAT_MULAI', 'MUAT_SELESAI']].dtypes)
display(combined_rkbm[['BONGKAR_MULAI', 'BONGKAR_SELESAI', 'MUAT_MULAI', 'MUAT_SELESAI']].head())

Tipe data kolom setelah standarisasi:
BONGKAR_MULAI      datetime64[ns]
BONGKAR_SELESAI    datetime64[ns]
MUAT_MULAI         datetime64[ns]
MUAT_SELESAI       datetime64[ns]
dtype: object

  BONGKAR_MULAI BONGKAR_SELESAI MUAT_MULAI MUAT_SELESAI
0    2023-04-02      2023-04-08        NaT          NaT
1           NaT             NaT 2023-08-24   2023-08-31
2           NaT             NaT 2023-02-12   2023-02-13
3    2023-04-01      2023-04-08        NaT          NaT
4    2023-01-06      2023-01-09 2023-01-06   2023-01-06

In [ ]:
print(combined_rkbm.info()) #dataframe_rkbm

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1437 entries, 0 to 1436
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   No                1437 non-null   object
 1   NOMOR RKBM        1437 non-null   object
 2   NOMOR PKK         1437 non-null   object
 3   PBM               1437 non-null   object
 4   Lokasi            1437 non-null   object
 5   AGEN              1437 non-null   object
 6   KAPAL             1437 non-null   object
 7   JENIS KAPAL       1437 non-null   object
 8   BENDERA           1437 non-null   object
 9   UKURAN_DWT        1437 non-null   int64
 10  UKURAN_GT         1437 non-null   int64
 11  UKURAN_LOA        1435 non-null   float64
 12  BONGKAR_MULAI     873 non-null    datetime64[ns]
 13  BONGKAR_SELESAI   873 non-null    datetime64[ns]
 14  BONGKAR_SISTEM    1437 non-null   object
 15  BONGKAR_KOMODITI  1437 non-null   object
 16  BONGKAR_JENIS     1437 non-null   object
 17  BONGKAR_TON       1437 non-null   object
 18  BONGKAR_UNIT      1437 non-null   object
 19  BONGKAR_M3        1437 non-null   object
 20  MUAT_MULAI        758 non-null    datetime64[ns]
 21  MUAT_SELESAI      758 non-null    datetime64[ns]
 22  MUAT_SISTEM       1437 non-null   object
 23  MUAT_KOMODITI     1437 non-null   object
 24  MUAT_JENIS        1437 non-null   object
 25  MUAT_TON          1437 non-null   object
 26  MUAT_UNIT         1437 non-null   object
 27  MUAT_M3           1437 non-null   object
 28  TGL APPROVE       1437 non-null   datetime64[ns]
 29  PETUGAS           1437 non-null   object
 30  source_file       1437 non-null   object
dtypes: datetime64[ns](5), float64(1), int64(2), object(23)
memory usage: 348.2+ KB
None

In [ ]:
#ekspor ke excell
from google.colab import files

# Mendefinisikan nama file
output_filename = 'combined_rkbm.xlsx'

# Ekspor dataframe ke Excel
combined_rkbm.to_excel(output_filename, index=False)

# Mengunduh file ke komputer lokal
files.download(output_filename)

print(f"Dataframe berhasil diekspor ke {output_filename} dan proses unduhan dimulai.")

Dataframe berhasil diekspor ke combined_rkbm.xlsx dan proses unduhan dimulai.

# pkk

In [ ]:
import pandas as pd
import io
import hashlib
from google.colab import files
from IPython.display import display

# Meminta user untuk mengunggah file xls dari inaportnet
print("Silakan unggah file PKK (ext xls) yg diunduh dari Inapornet:")
uploaded = files.upload()

all_dfs = []

for filename in uploaded.keys():
    try:
        file_bytes = uploaded[filename]
        file_hash = hashlib.sha256(file_bytes).hexdigest()
        print(f"\nReading uploaded file: {filename}")

        dfs = pd.read_html(io.BytesIO(file_bytes))
        if dfs:
            df = dfs[0]
            # Menambahkan kolom source_file
            df['source_file'] = filename
            print(f"Berhasil mengimpor: {filename}")
            all_dfs.append(df)
    except Exception as e:
        try:
            df = pd.read_excel(io.BytesIO(uploaded[filename]), engine='xlrd')
            df['source_file'] = filename
            all_dfs.append(df)
            print(f"Berhasil mengimpor (Excel mode): {filename}")
        except Exception as e2:
            print(f"Gagal membaca {filename}: {e2}")

if all_dfs:
    combined_pkk = pd.concat(all_dfs, ignore_index=True)
    print("\nSemua file berhasil digabungkan dengan kolom 'source_file'.")
    display(combined_pkk.head(5))
else:
    print("Tidak ada data yang berhasil diimpor.")

Silakan unggah file PKK (ext xls) yg diunduh dari Inapornet:

Saving LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN).xls to LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
Saving LK3-PPK.IDLSW.2023-01-01.2023-12-31 (LN).xls to LK3-PPK.IDLSW.2023-01-01.2023-12-31 (LN) (1).xls
Saving LK3-PPK.IDLSW.2024-01-01.2024-12-31 [DN].xls to LK3-PPK.IDLSW.2024-01-01.2024-12-31 [DN] (1).xls
Saving LK3-PPK.IDLSW.2024-01-01.2024-12-31 [LN].xls to LK3-PPK.IDLSW.2024-01-01.2024-12-31 [LN] (1).xls

Reading uploaded file: LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
Berhasil mengimpor: LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls

Reading uploaded file: LK3-PPK.IDLSW.2023-01-01.2023-12-31 (LN) (1).xls
Berhasil mengimpor: LK3-PPK.IDLSW.2023-01-01.2023-12-31 (LN) (1).xls

Reading uploaded file: LK3-PPK.IDLSW.2024-01-01.2024-12-31 [DN] (1).xls
Berhasil mengimpor: LK3-PPK.IDLSW.2024-01-01.2024-12-31 [DN] (1).xls

Reading uploaded file: LK3-PPK.IDLSW.2024-01-01.2024-12-31 [LN] (1).xls
Berhasil mengimpor: LK3-PPK.IDLSW.2024-01-01.2024-12-31 [LN] (1).xls

Semua file berhasil digabungkan dengan kolom 'source_file'.

  No                               Agen            Kapal  \
  No                               Agen            Kapal
0  1  PT. PELAYARAN MULTI JAYA SAMUDERA      GARUDA ASIA
1  2    PT. PERTAMINA TRANS KONTINENTAL      PELAGOS ONE
2  3    PT. PERTAMINA TRANS KONTINENTAL    PAN MARINE 11
3  4    PT. PERTAMINA TRANS KONTINENTAL  TRANSKO ARAFURA
4  5    PT. PERTAMINA TRANS KONTINENTAL    LOGINDO STOUT

                          Tipe Kapal                       PKK  \
                          Tipe Kapal                       PKK
0         OIL TANKER / TANGKI MINYAK  PKK.DN.IDLSW.2212.000060
1         OIL TANKER / TANGKI MINYAK  PKK.DN.IDLSW.2212.000064
2                          CREW BOAT  PKK.DN.IDLSW.2212.000063
3         OIL TANKER / TANGKI MINYAK  PKK.DN.IDLSW.2212.000065
4  ANCHOR HANDLING TUG SUPPLY (AHTS)  PKK.DN.IDLSW.2212.000067

                       LK3               SPK KELUAR                     SPB  \
                       LK3               SPK KELUAR                     SPB
0  SL003.IDLSW.1222.000064       IDLSW-206509435924  SPB.IDLSW.1222.0000064
1  SL003.IDLSW.0123.000002  IDLSW-SPK-2301-000-0001  SPB.IDLSW.0123.0000001
2  SL003.IDLSW.0123.000001                      NaN  SPB.IDLSW.0123.0000002
3  SL003.IDLSW.0123.000003       IDLSW-202517530825  SPB.IDLSW.0123.0000003
4  SL003.IDLSW.0123.000004  IDLSW-SPK-2301-000-0002  SPB.IDLSW.0123.0000005

                 Nakhoda Bendera  ...                RKBM Muat                \
                 Nakhoda Bendera  ...             No RKBM Muat Komoditi Muat
0   Cecep Rahmat Gumilar      ID  ...                      NaN           NaN
1         BENYAMIN TASSO      ID  ...  SL004.IDLSW.1222.000058    CONDENSATE
2  ADITYA RIDWAN KOSASIH      ID  ...                      NaN           NaN
3            RENO KAMPAI      ID  ...                      NaN           NaN
4          BERTY SARANTI      ID  ...  SL004.IDLSW.1222.000059           NaN

                                          Penumpang Naik              NTPN  \
   Jenis Muat  Ton Muat Unit Muat M3 Muat Penumpang Naik              NTPN
0         NaN       NaN       NaN     NaN            NaN  8FE2C3CIF28NHIOB
1  Curah Cair  100000.0       0.0     0.0            NaN  9B1846U8EKQK9ILF
2         NaN       NaN       NaN     NaN            2.0  565E27QLUFD0MILG
3         NaN       NaN       NaN     NaN            NaN  FA6377QLUFD0MOI8
4         NaN       NaN       NaN     NaN            2.0  8A84E1JNFLCASB7V

  Nilai Billing                                       source_file
  Nilai Billing
0        409220  LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
1      15619250  LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
2         40250  LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
3        732500  LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
4        154129  LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls

[5 rows x 51 columns]

In [ ]:
# Memeriksa apakah terdapat MultiIndex pada kolom combined_pkk
if isinstance(combined_pkk.columns, pd.MultiIndex):
    print("Multi-index terdeteksi pada combined_pkk. Melakukan perbaikan...")

    # Menggabungkan level index menjadi satu nama string yang rapi
    new_columns = []
    for col in combined_pkk.columns:
        # Jika level kedua kosong atau sama dengan level pertama, ambil level pertama saja
        if str(col[1]).strip() == "" or col[0] == col[1]:
            new_columns.append(col[0])
        else:
            new_columns.append(f"{col[0]}_{col[1]}")

    combined_pkk.columns = new_columns
    print("Header combined_pkk telah diperbaiki menjadi single-index.")
else:
    print("Dataframe combined_pkk sudah menggunakan single-index.")

# Menampilkan info kolom dan preview
print("\nKolom combined_pkk saat ini:")
print(combined_pkk.columns.tolist())
display(combined_pkk.head())

Multi-index terdeteksi pada combined_pkk. Melakukan perbaikan...
Header combined_pkk telah diperbaiki menjadi single-index.

Kolom combined_pkk saat ini:
['No', 'Agen', 'Kapal', 'Tipe Kapal', 'PKK', 'LK3', 'SPK KELUAR', 'SPB', 'Nakhoda', 'Bendera', 'IMO', 'Tanda Pendaftaran Kapal', 'Call Sign', 'Ukuran_DWT', 'Ukuran_GT', 'Ukuran_LOA', 'Trayek', 'Jumlah Awak', 'Muatan', 'Pelabuhan Asal', 'Tgl Tiba', 'Pelabuhan Tujuan', 'Tanggal Tolak', 'Posisi Tolak', 'Tanggal Terbit SPB', 'RPKRO', 'PPK', 'PPKB', 'No SPK', 'Dermaga', 'Mulai', 'Selesai', 'RKBM Bongkar_PBM Bongkar', 'RKBM Bongkar_No RKBM Bongkar', 'RKBM Bongkar_Komoditi Bongkar', 'RKBM Bongkar_Jenis Bongkar', 'RKBM Bongkar_Ton Bongkar', 'RKBM Bongkar_Unit Bongkar', 'RKBM Bongkar_M3 Bongkar', 'Penumpang Turun', 'RKBM Muat_PBM Muat', 'RKBM Muat_No RKBM Muat', 'RKBM Muat_Komoditi Muat', 'RKBM Muat_Jenis Muat', 'RKBM Muat_Ton Muat', 'RKBM Muat_Unit Muat', 'RKBM Muat_M3 Muat', 'Penumpang Naik', 'NTPN', 'Nilai Billing', 'source_file']

,No,Agen,Kapal,Tipe Kapal,PKK,LK3,SPK KELUAR,SPB,Nakhoda,Bendera,...,RKBM Muat_No RKBM Muat,RKBM Muat_Komoditi Muat,RKBM Muat_Jenis Muat,RKBM Muat_Ton Muat,RKBM Muat_Unit Muat,RKBM Muat_M3 Muat,Penumpang Naik,NTPN,Nilai Billing,source_file
0,1,PT. PELAYARAN MULTI JAYA SAMUDERA,GARUDA ASIA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000060,SL003.IDLSW.1222.000064,IDLSW-206509435924,SPB.IDLSW.1222.0000064,Cecep Rahmat Gumilar,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8FE2C3CIF28NHIOB,409220,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SL003.IDLSW.0123.000002,IDLSW-SPK-2301-000-0001,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,...,SL004.IDLSW.1222.000058,CONDENSATE,Curah Cair,100000.0,0.0,0.0,NaN,9B1846U8EKQK9ILF,15619250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SL003.IDLSW.0123.000001,NaN,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,565E27QLUFD0MILG,40250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SL003.IDLSW.0123.000003,IDLSW-202517530825,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FA6377QLUFD0MOI8,732500,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SL003.IDLSW.0123.000004,IDLSW-SPK-2301-000-0002,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,...,SL004.IDLSW.1222.000059,NaN,NaN,NaN,NaN,NaN,2.0,8A84E1JNFLCASB7V,154129,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls

In [ ]:
print(f"Jumlah baris sebelum penghapusan duplikat: {len(combined_pkk)}")

duplicate_rows = combined_pkk.duplicated().sum()

if duplicate_rows > 0:
    print(f"Ditemukan {duplicate_rows} baris duplikat di combined_pkk. Membersihkan...")
    combined_pkk = combined_pkk.drop_duplicates(keep='first')
    print(f"Jumlah baris setelah penghapusan duplikat: {len(combined_pkk)}")
    print("Duplikat berhasil dihapus.")
else:
    print("Tidak ditemukan baris duplikat di combined_pkk.")

display(combined_pkk.head())

Jumlah baris sebelum penghapusan duplikat: 3886
Ditemukan 16 baris duplikat di combined_pkk. Membersihkan...
Jumlah baris setelah penghapusan duplikat: 3870
Duplikat berhasil dihapus.

,No,Agen,Kapal,Tipe Kapal,PKK,LK3,SPK KELUAR,SPB,Nakhoda,Bendera,...,RKBM Muat_No RKBM Muat,RKBM Muat_Komoditi Muat,RKBM Muat_Jenis Muat,RKBM Muat_Ton Muat,RKBM Muat_Unit Muat,RKBM Muat_M3 Muat,Penumpang Naik,NTPN,Nilai Billing,source_file
0,1,PT. PELAYARAN MULTI JAYA SAMUDERA,GARUDA ASIA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000060,SL003.IDLSW.1222.000064,IDLSW-206509435924,SPB.IDLSW.1222.0000064,Cecep Rahmat Gumilar,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8FE2C3CIF28NHIOB,409220,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SL003.IDLSW.0123.000002,IDLSW-SPK-2301-000-0001,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,...,SL004.IDLSW.1222.000058,CONDENSATE,Curah Cair,100000.0,0.0,0.0,NaN,9B1846U8EKQK9ILF,15619250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SL003.IDLSW.0123.000001,NaN,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,565E27QLUFD0MILG,40250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SL003.IDLSW.0123.000003,IDLSW-202517530825,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FA6377QLUFD0MOI8,732500,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SL003.IDLSW.0123.000004,IDLSW-SPK-2301-000-0002,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,...,SL004.IDLSW.1222.000059,NaN,NaN,NaN,NaN,NaN,2.0,8A84E1JNFLCASB7V,154129,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls

In [ ]:
# Ensure combined_pkk is an independent copy to prevent SettingWithCopyWarning issues
combined_pkk = combined_pkk.copy()

# 1. Merubah kolom No menjadi string menggunakan .loc untuk menghindari warning
combined_pkk.loc[:, 'No'] = combined_pkk['No'].astype(str)

# 2. Daftar kolom yang akan dikonversi ke datetime
date_cols_pkk = [
    'Tgl Tiba',
    'Tanggal Tolak',
    'Tanggal Terbit SPB',
    'Mulai',
    'Selesai'
]

# Menampilkan info untuk verifikasi tipe data sebelum perubahan
print("Verifikasi tipe data sebelum perubahan:")
print(combined_pkk[['No'] + [c for c in date_cols_pkk if c in combined_pkk.columns]].dtypes)

# 3. Proses konversi ke datetime menggunakan .loc dengan debug tambahan
for col in date_cols_pkk:
    if col in combined_pkk.columns:
        print(f"\nProcessing column: {col}")
        original_dtype = combined_pkk[col].dtype
        print(f"  Original Dtype: {original_dtype}")
        # Convert to string first and then to datetime with a specific format
        # Use format='%Y-%m-%d %H:%M:%S' based on observed sample data
        converted_series = pd.to_datetime(combined_pkk[col].astype(str), format='%Y-%m-%d %H:%M:%S', errors='coerce')
        # Debug: Check converted_series dtype
        print(f"  Dtype of converted_series: {converted_series.dtype}")
        # Assign the converted series directly to the column (removed .loc for direct assignment)
        combined_pkk[col] = converted_series
        # Debug: Check dtype immediately after assignment
        print(f"  Dtype after conversion and assignment: {combined_pkk[col].dtype}")
    else:
        print(f"\nColumn '{col}' not found in combined_pkk. Skipping conversion.")

# Menampilkan info untuk verifikasi perubahan akhir
print("\nVerifikasi tipe data baru:")
print(combined_pkk[['No'] + [c for c in date_cols_pkk if c in combined_pkk.columns]].dtypes)
display(combined_pkk.head(5))

Verifikasi tipe data sebelum perubahan:
No                    object
Tgl Tiba              object
Tanggal Tolak         object
Tanggal Terbit SPB    object
Mulai                 object
Selesai               object
dtype: object

Processing column: Tgl Tiba
  Original Dtype: object
  Dtype of converted_series: datetime64[ns]
  Dtype after conversion and assignment: datetime64[ns]

Processing column: Tanggal Tolak
  Original Dtype: object
  Dtype of converted_series: datetime64[ns]
  Dtype after conversion and assignment: datetime64[ns]

Processing column: Tanggal Terbit SPB
  Original Dtype: object
  Dtype of converted_series: datetime64[ns]
  Dtype after conversion and assignment: datetime64[ns]

Processing column: Mulai
  Original Dtype: object
  Dtype of converted_series: datetime64[ns]
  Dtype after conversion and assignment: datetime64[ns]

Processing column: Selesai
  Original Dtype: object
  Dtype of converted_series: datetime64[ns]
  Dtype after conversion and assignment: datetime64[ns]

Verifikasi tipe data baru:
No                            object
Tgl Tiba              datetime64[ns]
Tanggal Tolak         datetime64[ns]
Tanggal Terbit SPB    datetime64[ns]
Mulai                 datetime64[ns]
Selesai               datetime64[ns]
dtype: object

/tmp/ipykernel_5426/2350043492.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' ... '1040' '1041' '1042']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  combined_pkk.loc[:, 'No'] = combined_pkk['No'].astype(str)

,No,Agen,Kapal,Tipe Kapal,PKK,LK3,SPK KELUAR,SPB,Nakhoda,Bendera,...,RKBM Muat_No RKBM Muat,RKBM Muat_Komoditi Muat,RKBM Muat_Jenis Muat,RKBM Muat_Ton Muat,RKBM Muat_Unit Muat,RKBM Muat_M3 Muat,Penumpang Naik,NTPN,Nilai Billing,source_file
0,1,PT. PELAYARAN MULTI JAYA SAMUDERA,GARUDA ASIA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000060,SL003.IDLSW.1222.000064,IDLSW-206509435924,SPB.IDLSW.1222.0000064,Cecep Rahmat Gumilar,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8FE2C3CIF28NHIOB,409220,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
1,2,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SL003.IDLSW.0123.000002,IDLSW-SPK-2301-000-0001,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,...,SL004.IDLSW.1222.000058,CONDENSATE,Curah Cair,100000.0,0.0,0.0,NaN,9B1846U8EKQK9ILF,15619250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
2,3,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SL003.IDLSW.0123.000001,NaN,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,565E27QLUFD0MILG,40250,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
3,4,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SL003.IDLSW.0123.000003,IDLSW-202517530825,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FA6377QLUFD0MOI8,732500,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SL003.IDLSW.0123.000004,IDLSW-SPK-2301-000-0002,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,...,SL004.IDLSW.1222.000059,NaN,NaN,NaN,NaN,NaN,2.0,8A84E1JNFLCASB7V,154129,LK3-PPK.IDLSW.2023-01-01.2023-12-31 (DN) (1).xls

In [ ]:
print("Menampilkan sampel data yang gagal dikonversi ke datetime (NaN setelah coerce):")
for col in date_cols_pkk:
    if col in combined_pkk_clean.columns:
        # Lakukan konversi ulang dengan errors='coerce' untuk mendapatkan NaT bagi yang gagal
        converted = pd.to_datetime(combined_pkk_clean[col].astype(str), format='%Y-%m-%d %H:%M:%S', errors='coerce')

        # Bandingkan dengan NaT untuk menemukan baris yang gagal
        failed_mask = converted.isna()

        # Ambil nilai asli dari kolom yang gagal dikonversi
        problematic_values = combined_pkk_clean.loc[failed_mask, col].unique()

        if len(problematic_values) > 0:
            print(f"\nKolom '{col}' memiliki {len(problematic_values)} nilai unik yang gagal dikonversi:")
            for val in problematic_values[:10]: # Tampilkan hingga 10 nilai problematic
                print(f"  - {val}")
        else:
            print(f"\nKolom '{col}': Semua nilai berhasil dikonversi atau sudah NaT.")
    else:
        print(f"\nKolom '{col}' tidak ditemukan di combined_pkk_clean.")

Menampilkan sampel data yang gagal dikonversi ke datetime (NaN setelah coerce):

Kolom 'Tgl Tiba': Semua nilai berhasil dikonversi atau sudah NaT.

Kolom 'Tanggal Tolak': Semua nilai berhasil dikonversi atau sudah NaT.

Kolom 'Tanggal Terbit SPB': Semua nilai berhasil dikonversi atau sudah NaT.

Kolom 'Mulai' memiliki 1 nilai unik yang gagal dikonversi:
  - nan

Kolom 'Selesai' memiliki 1 nilai unik yang gagal dikonversi:
  - nan

In [ ]:
print(combined_pkk.info()) #dataframe_pkk yg sudah bersih

<class 'pandas.core.frame.DataFrame'>
Index: 3870 entries, 0 to 3885
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   No                             3870 non-null   object
 1   Agen                           3870 non-null   object
 2   Kapal                          3870 non-null   object
 3   Tipe Kapal                     3870 non-null   object
 4   PKK                            3870 non-null   object
 5   LK3                            3868 non-null   object
 6   SPK KELUAR                     3494 non-null   object
 7   SPB                            3846 non-null   object
 8   Nakhoda                        3802 non-null   object
 9   Bendera                        3870 non-null   object
 10  IMO                            3430 non-null   object
 11  Tanda Pendaftaran Kapal        3870 non-null   object
 12  Call Sign                      3814 non-null   object
 13  Ukuran_DWT                     3870 non-null   int64
 14  Ukuran_GT                      3870 non-null   int64
 15  Ukuran_LOA                     3870 non-null   float64
 16  Trayek                         3870 non-null   object
 17  Jumlah Awak                    3870 non-null   int64
 18  Muatan                         3870 non-null   object
 19  Pelabuhan Asal                 3870 non-null   object
 20  Tgl Tiba                       3870 non-null   datetime64[ns]
 21  Pelabuhan Tujuan               3870 non-null   object
 22  Tanggal Tolak                  3870 non-null   datetime64[ns]
 23  Posisi Tolak                   3870 non-null   object
 24  Tanggal Terbit SPB             3870 non-null   datetime64[ns]
 25  RPKRO                          3868 non-null   object
 26  PPK                            3868 non-null   object
 27  PPKB                           3870 non-null   object
 28  No SPK                         3398 non-null   object
 29  Dermaga                        3868 non-null   object
 30  Mulai                          3868 non-null   datetime64[ns]
 31  Selesai                        3868 non-null   datetime64[ns]
 32  RKBM Bongkar_PBM Bongkar       1530 non-null   object
 33  RKBM Bongkar_No RKBM Bongkar   1588 non-null   object
 34  RKBM Bongkar_Komoditi Bongkar  1530 non-null   object
 35  RKBM Bongkar_Jenis Bongkar     1530 non-null   object
 36  RKBM Bongkar_Ton Bongkar       1530 non-null   float64
 37  RKBM Bongkar_Unit Bongkar      1530 non-null   float64
 38  RKBM Bongkar_M3 Bongkar        1530 non-null   float64
 39  Penumpang Turun                152 non-null    float64
 40  RKBM Muat_PBM Muat             424 non-null    object
 41  RKBM Muat_No RKBM Muat         778 non-null    object
 42  RKBM Muat_Komoditi Muat        424 non-null    object
 43  RKBM Muat_Jenis Muat           424 non-null    object
 44  RKBM Muat_Ton Muat             424 non-null    float64
 45  RKBM Muat_Unit Muat            424 non-null    float64
 46  RKBM Muat_M3 Muat              424 non-null    float64
 47  Penumpang Naik                 196 non-null    float64
 48  NTPN                           3815 non-null   object
 49  Nilai Billing                  3870 non-null   int64
 50  source_file                    3870 non-null   object
dtypes: datetime64[ns](5), float64(9), int64(4), object(33)
memory usage: 1.5+ MB
None

In [ ]:
# Ekspor dataframe combined_pkk yang sudah final
output_pkk = 'combined_pkk.xlsx'

# Ekspor ke Excel
combined_pkk.to_excel(output_pkk, index=False)

# Unduh file
files.download(output_pkk)

print(f"Dataframe final berhasil diekspor ke {output_pkk} dan proses unduhan dimulai.")

Dataframe final berhasil diekspor ke combined_pkk_clean.xlsx dan proses unduhan dimulai.

# Append SPB & SPOG

In [ ]:
# 1. Buat dataframe baru combined_spb_mod dengan rename kolom
combined_spb_mod = combined_spb.rename(columns={
    'SPB': 'No Layanan',
    'Posisi Tolak': 'Dari',
    'No SPK': 'SPK'
}).copy()

# 2. Tambahkan kolom baru 'Ke' dengan isi 'Laut' pada dataframe baru
combined_spb_mod['Ke'] = 'Laut'

# Verifikasi perubahan pada combined_spb_mod
print("Dataframe combined_spb_mod berhasil dibuat:")
display(combined_spb_mod[['No Layanan', 'Dari', 'SPK', 'Ke']].head(5))

Dataframe combined_spb_mod berhasil dibuat:

,No Layanan,Dari,SPK,Ke
0,SPB.IDLSW.0123.0000001,TUKS PAG - DERMAGA V (MARGINAL),IDLSW-SPK-2301-000-0001,Laut
1,SPB.IDLSW.0123.0000002,TUKS PAG - DERMAGA II (MARGINAL),NaN,Laut
2,SPB.IDLSW.0123.0000003,TUKS PERTAMINA - MULTIPURPOSE,IDLSW-202517530825,Laut
3,SPB.IDLSW.0123.0000004,Area Labuh Kapal General Cargo,NaN,Laut
4,SPB.IDLSW.0123.0000005,TUKS PAG - DERMAGA II (MARGINAL),IDLSW-SPK-2301-000-0002,Laut

In [ ]:
import pandas as pd
from IPython.display import display

# 1. Buat dataframe baru combined_spog_mod dengan rename kolom
combined_spog_mod = combined_spog.rename(columns={'No SPOG': 'No Layanan'}).copy()

# 2. Verifikasi perubahan
print("Dataframe combined_spog_mod berhasil dibuat dengan kolom 'No Layanan':")
display(combined_spog_mod[['No Layanan', 'Kapal', 'PKK']].head(5))

# 3. Opsional: Menampilkan info kolom untuk memastikan
print("\nInfo kolom combined_spog_mod:")
print(combined_spog_mod.columns.tolist())

Dataframe combined_spog_mod berhasil dibuat dengan kolom 'No Layanan':

                No Layanan              Kapal                       PKK
0  SPOG.IDLSW.0123.0000001          BERAU MAS  PKK.DN.IDLSW.2212.000068
1  SPOG.IDLSW.0123.0000002      LOGINDO STOUT  PKK.DN.IDLSW.2212.000067
2  SPOG.IDLSW.0123.0000003  RAMFORM SOVEREIGN  PKK.LN.IDLSW.2301.000002
3  SPOG.IDLSW.0123.0000004   AEROSEA CATALINA  PKK.DN.IDLSW.2301.000001
4  SPOG.IDLSW.0123.0000005      PAN MARINE 11  PKK.DN.IDLSW.2301.000003

Info kolom combined_spog_mod:
['No', 'Agen', 'Kapal', 'Tipe Kapal', 'PKK', 'No Layanan', 'Nakhoda', 'Bendera', 'IMO', 'Tanda Pendaftaran Kapal', 'Call Sign', 'GT', 'LOA', 'Dari', 'Ke', 'Tujuan', 'Pandu', 'SPK', 'Petugas', 'Waktu Gerak', 'source_file']

In [ ]:
import pandas as pd
from IPython.display import display

# 1. Periksa perbedaan kolom sebelum penggabungan
cols_spb2 = set(combined_spb_mod.columns)
cols_spog2 = set(combined_spog_mod.columns)

print("--- Analisis Kolom ---")
print(f"Kolom unik di combined_spb_mod: {cols_spb2 - cols_spog2}")
print(f"Kolom unik di combined_spog_mod: {cols_spog2 - cols_spb2}")

# 2. Gabungkan dataframes
# Menggunakan concat (outer join) untuk mempertahankan semua kolom
combined_spbspog = pd.concat([combined_spb_mod, combined_spog_mod], ignore_index=True, sort=False)

# 3. Periksa baris duplikat
duplicate_mask = combined_spbspog.duplicated(keep=False)
num_duplicates = duplicate_mask.sum()

print(f"\n--- Analisis Baris ---")
print(f"Total baris setelah penggabungan: {len(combined_spbspog)}")
print(f"Jumlah baris duplikat ditemukan: {num_duplicates}")

if num_duplicates > 0:
    print("Preview baris duplikat (5 baris pertama):")
    display(combined_spbspog[duplicate_mask].head(5))
else:
    print("Tidak ditemukan baris duplikat.")

# Tampilkan 5 baris pertama hasil penggabungan
print("\nPreview hasil penggabungan:")
display(combined_spbspog.head())

--- Analisis Kolom ---
Kolom unik di combined_spb_mod: {'Pelabuhan Tujuan', 'NTPN Labuh', 'Jumlah Awak', 'Billing Labuh', 'NTPN Rambu', 'Muatan', 'Billing Rambu', 'Tanggal Terbit', 'Pelabuhan Asal', 'Tanggal Tiba', 'Tanggal Tolak'}
Kolom unik di combined_spog_mod: {'Waktu Gerak', 'Pandu', 'Tujuan'}

--- Analisis Baris ---
Total baris setelah penggabungan: 3570
Jumlah baris duplikat ditemukan: 0
Tidak ditemukan baris duplikat.

Preview hasil penggabungan:

,No,Agen,Kapal,Tipe Kapal,PKK,No Layanan,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,NTPN Labuh,Billing Rambu,NTPN Rambu,Petugas,SPK,source_file,Ke,Tujuan,Pandu,Waktu Gerak
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,195796U8EKQK9HPV,'820230101617327,9B1846U8EKQK9ILF,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0001,SPB.IDLSW.01.2023.xls,Laut,NaN,NaN,NaT
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,70F0B2G4VFUM8GUK,'820230101617328,565E27QLUFD0MILG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls,Laut,NaN,NaN,NaT
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,F9EFD7QLUFD0MRAC,'820230101623368,FA6377QLUFD0MOI8,"YUSRIADI, A. Md",IDLSW-202517530825,SPB.IDLSW.01.2023.xls,Laut,NaN,NaN,NaT
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,C05CE55DEVLSGB8N,'820230102665872,4F31C2G4VFUN8IKG,"YUSRIADI, A. Md",NaN,SPB.IDLSW.01.2023.xls,Laut,NaN,NaN,NaT
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,8A84E1JNFLCASB7V,'820230102681149,41E708N3E9VE41HT,"YUSRIADI, A. Md",IDLSW-SPK-2301-000-0002,SPB.IDLSW.01.2023.xls,Laut,NaN,NaN,NaT

#upload data dermaga

In [ ]:
import pandas as pd
from google.colab import files
import io

# 1. Meminta user mengunggah file
print("Silakan unggah file Excel Data Dermaga:")
uploaded_dermaga = files.upload()

# 2. Membaca file yang diunggah menjadi dataframe
for filename in uploaded_dermaga.keys():
    df_dermaga = pd.read_excel(io.BytesIO(uploaded_dermaga[filename]))
    print(f"\nBerhasil mengimpor {filename} sebagai dataframe 'df_dermaga'.")

# 3. Menampilkan preview data
display(df_dermaga.head())

Silakan unggah file Excel Data Dermaga:

Saving Data Dermaga.xlsx to Data Dermaga.xlsx

Berhasil mengimpor Data Dermaga.xlsx sebagai dataframe 'df_dermaga'.

,Kode Dermaga,Nama Dermaga,Wajib Pandu?,TERSUS?,TUKS?,STATUS?
0,IDLSW.LS.L7,Area Labuh Emergency,Tidak,Tidak,Tidak,Ya
1,IDLSW.LS.L3,Area Labuh Kapal BBM,Tidak,Tidak,Tidak,Ya
2,IDLSW.LS.L2,Area Labuh Kapal Bermuatan Bahan Kimia,Tidak,Tidak,Tidak,Ya
3,IDLSW.LS.L5,Area Labuh Kapal Curah Cair,Tidak,Tidak,Tidak,Ya
4,IDLSW.LS.L4,Area Labuh Kapal Curah Kering,Tidak,Tidak,Tidak,Ya

SPB&SPOG -> data dermaga

In [ ]:
import pandas as pd
from IPython.display import display

# 1. Melakukan merge pertama berdasarkan kolom 'Dari'
merge_dari = pd.merge(
    combined_spbspog,
    df_dermaga,
    left_on='Dari',
    right_on='Nama Dermaga',
    how='left'
)

# 2. Identifikasi baris yang tidak cocok pada merge pertama
mask_nan = merge_dari['Nama Dermaga'].isna()
df_needs_fallback = combined_spbspog[mask_nan].copy()

# 3. Melakukan merge kedua (fallback) berdasarkan kolom 'Ke' untuk baris yang tidak cocok
merge_ke = pd.merge(
    df_needs_fallback,
    df_dermaga,
    left_on='Ke',
    right_on='Nama Dermaga',
    how='left'
)

# 4. Menggabungkan hasil (Baris yang cocok dari 'Dari' + Hasil merge dari 'Ke')
# Ambil baris yang sudah cocok dari merge pertama
combined_match_dari = merge_dari[~mask_nan].copy()

# Gabungkan kembali
combined_final_all = pd.concat([combined_match_dari, merge_ke], ignore_index=True)

# 5. Memisahkan hasil akhir dengan nama baru sesuai permintaan user
combined_spbspog_dermaga = combined_final_all[combined_final_all['Nama Dermaga'].notna()].copy()
combined_spbspog_dermaga_NaN = combined_final_all[combined_final_all['Nama Dermaga'].isna()].copy()

# Verifikasi hasil
print(f"Total baris diproses: {len(combined_spbspog_dermaga) + len(combined_spbspog_dermaga_NaN)}")
print(f"Jumlah baris cocok (combined_spbspog_dermaga): {len(combined_spbspog_dermaga)}")
print(f"Jumlah baris tidak cocok (combined_spbspog_dermaga_NaN): {len(combined_spbspog_dermaga_NaN)}")

print("\nPreview data yang cocok (combined_spbspog_dermaga):")
display(combined_spbspog_dermaga.head(3))

print("\nPreview data yang tidak cocok (combined_spbspog_dermaga_NaN):")
display(combined_spbspog_dermaga_NaN[['No Layanan', 'Dari', 'Ke']].head(3))

Total baris diproses: 3570
Jumlah baris cocok (combined_spbspog_dermaga): 3570
Jumlah baris tidak cocok (combined_spbspog_dermaga_NaN): 0

Preview data yang cocok (combined_spbspog_dermaga):

,No,Agen,Kapal,Tipe Kapal,PKK,No Layanan,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Ke,Tujuan,Pandu,Waktu Gerak,Kode Dermaga,Nama Dermaga,Wajib Pandu?,TERSUS?,TUKS?,STATUS?
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D05,TUKS PAG - DERMAGA V (MARGINAL),Ya,Tidak,Ya,Ya
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D02,TUKS PAG - DERMAGA II (MARGINAL),Ya,Tidak,Ya,Ya
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,Laut,NaN,NaN,NaT,IDLSW.L03.D01,TUKS PERTAMINA - MULTIPURPOSE,Ya,Tidak,Ya,Ya

Preview data yang tidak cocok (combined_spbspog_dermaga_NaN):

Empty DataFrame
Columns: [No Layanan, Dari, Ke]
Index: []

In [ ]:
from google.colab import files
import pandas as pd

def export_dataframe_by_name():
    """
    Meminta input nama variabel dataframe dari user,
    lalu mengekspornya ke Excel.
    """
    df_name = input("Masukkan nama variabel dataframe yang ingin diekspor (contoh: combined_spbspog_dermaga): ").strip()

    # Memeriksa apakah variabel ada di namespace global
    if df_name in globals():
        df = globals()[df_name]

        if isinstance(df, pd.DataFrame):
            filename = f"{df_name}.xlsx"
            df.to_excel(filename, index=False)
            files.download(filename)
            print(f"Berhasil! Dataframe '{df_name}' sedang diunduh sebagai '{filename}'.")
        else:
            print(f"Error: '{df_name}' bukan merupakan Pandas DataFrame.")
    else:
        print(f"Error: Variabel '{df_name}' tidak ditemukan.")

# Jalankan fungsi
export_dataframe_by_name()

Masukkan nama variabel dataframe yang ingin diekspor (contoh: combined_spbspog_dermaga): combined_spbspog_dermaga_NaN

Berhasil! Dataframe 'combined_spbspog_dermaga_NaN' sedang diunduh sebagai 'combined_spbspog_dermaga_NaN.xlsx'.

#split dataframe based on SPK fill

In [ ]:
import pandas as pd

# Memisahkan dataframe berdasarkan kolom 'SPK'
# 1. Baris yang memiliki SPK (tidak NaN)
combined_spbspog_dermaga_SPK = combined_spbspog_dermaga[combined_spbspog_dermaga['SPK'].notna()].copy()

# 2. Baris yang tidak memiliki SPK (NaN)
combined_spbspog_dermaga_NoSPK = combined_spbspog_dermaga[combined_spbspog_dermaga['SPK'].isna()].copy()

# Verifikasi jumlah baris
print(f"Total baris di combined_spbspog_dermaga: {len(combined_spbspog_dermaga)}")
print(f"Baris dengan SPK: {len(combined_spbspog_dermaga_SPK)}")
print(f"Baris tanpa SPK: {len(combined_spbspog_dermaga_NoSPK)}")

print("\nPreview Data dengan SPK:")
display(combined_spbspog_dermaga_SPK.head(3))

print("\nPreview Data tanpa SPK:")
display(combined_spbspog_dermaga_NoSPK.head(3))

Total baris di combined_spbspog_dermaga: 3570
Baris dengan SPK: 3241
Baris tanpa SPK: 329

Preview Data dengan SPK:

,No,Agen,Kapal,Tipe Kapal,PKK,No Layanan,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Ke,Tujuan,Pandu,Waktu Gerak,Kode Dermaga,Nama Dermaga,Wajib Pandu?,TERSUS?,TUKS?,STATUS?
0,1,PT. PERTAMINA TRANS KONTINENTAL,PELAGOS ONE,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000064,SPB.IDLSW.0123.0000001,BENYAMIN TASSO,ID,9299898.0,2020 PPa No. 5593/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D05,TUKS PAG - DERMAGA V (MARGINAL),Ya,Tidak,Ya,Ya
2,3,PT. PERTAMINA TRANS KONTINENTAL,TRANSKO ARAFURA,OIL TANKER / TANGKI MINYAK,PKK.DN.IDLSW.2212.000065,SPB.IDLSW.0123.0000003,RENO KAMPAI,ID,9774874.0,2017 Pst No. 9292/L,...,Laut,NaN,NaN,NaT,IDLSW.L03.D01,TUKS PERTAMINA - MULTIPURPOSE,Ya,Tidak,Ya,Ya
4,5,PT. PERTAMINA TRANS KONTINENTAL,LOGINDO STOUT,ANCHOR HANDLING TUG SUPPLY (AHTS),PKK.DN.IDLSW.2212.000067,SPB.IDLSW.0123.0000005,BERTY SARANTI,ID,9548639.0,2013 Pst No. 8035/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D02,TUKS PAG - DERMAGA II (MARGINAL),Ya,Tidak,Ya,Ya

Preview Data tanpa SPK:

,No,Agen,Kapal,Tipe Kapal,PKK,No Layanan,Nakhoda,Bendera,IMO,Tanda Pendaftaran Kapal,...,Ke,Tujuan,Pandu,Waktu Gerak,Kode Dermaga,Nama Dermaga,Wajib Pandu?,TERSUS?,TUKS?,STATUS?
1,2,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2212.000063,SPB.IDLSW.0123.0000002,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D02,TUKS PAG - DERMAGA II (MARGINAL),Ya,Tidak,Ya,Ya
3,4,PT. PELAYARAN NASIONAL INDONESIA (PELNI),RAMFORM SOVEREIGN,SEISMIC SURVEY VESSEL,PKK.LN.IDLSW.2301.000002,SPB.IDLSW.0123.0000004,"Honningsvaag, Paul Erling",BS,9390460.0,9390460,...,Laut,NaN,NaN,NaT,IDLSW.LS.L1,Area Labuh Kapal General Cargo,Tidak,Tidak,Tidak,Ya
5,6,PT. PERTAMINA TRANS KONTINENTAL,PAN MARINE 11,CREW BOAT,PKK.DN.IDLSW.2301.000003,SPB.IDLSW.0123.0000006,ADITYA RIDWAN KOSASIH,ID,9441817.0,2007 Pst No. 4734/L,...,Laut,NaN,NaN,NaT,IDLSW.L04.D02,TUKS PAG - DERMAGA II (MARGINAL),Ya,Tidak,Ya,Ya

In [ ]:
import numpy as np

# Definisikan kondisi untuk masing-masing kriteria
cond_pandu_tunda = (combined_spbspog_dermaga_NoSPK['GT'] >= 500) & (combined_spbspog_dermaga_NoSPK['LOA'] >= 70)
cond_pandu_only = (combined_spbspog_dermaga_NoSPK['GT'] >= 500) & (combined_spbspog_dermaga_NoSPK['LOA'] < 70)

# Mengisi kolom RedFlag1 berdasarkan hierarki kondisi
combined_spbspog_dermaga_NoSPK['RedFlag1'] = ""
combined_spbspog_dermaga_NoSPK.loc[cond_pandu_only, 'RedFlag1'] = "Seharusnya Pandu karena GT>=500"
combined_spbspog_dermaga_NoSPK.loc[cond_pandu_tunda, 'RedFlag1'] = "Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m"

# Filter untuk melihat baris yang terkena RedFlag1
redflag_results = combined_spbspog_dermaga_NoSPK[combined_spbspog_dermaga_NoSPK['RedFlag1'] != ""]

print(f"Jumlah baris yang masuk kriteria RedFlag1: {len(redflag_results)}")
display(redflag_results[['No Layanan', 'Kapal', 'GT', 'LOA', 'STATUS?', 'RedFlag1']].head(10))

Jumlah baris yang masuk kriteria RedFlag1: 35

,No Layanan,Kapal,GT,LOA,STATUS?,RedFlag1
3,SPB.IDLSW.0123.0000004,RAMFORM SOVEREIGN,13688,102.20,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
73,SPB.IDLSW.0124.0000009,BAHTERA SUKSES,2849,96.00,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
275,SPB.IDLSW.0323.0000033,LOGINDO STURDY,1986,70.05,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
342,SPB.IDLSW.0324.0000039,PACIFIC HARRIER,4059,88.10,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
343,SPB.IDLSW.0324.0000040,WEST CAPELLA,59626,21133.00,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
346,SPB.IDLSW.0324.0000044,PACIFIC LEGACY,5179,97.40,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
395,SPB.IDLSW.0423.0000009,RV GARDA,610,49.60,Ya,Seharusnya Pandu karena GT>=500
422,SPB.IDLSW.0423.0000036,TENEO,3111,81.00,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
480,SPB.IDLSW.0424.0000048,ANGGREK 601,2596,72.11,Ya,Seharusnya Pandu&Tunda karena GT>=500 & LoA >=70m
566,SPB.IDLSW.0523.0000050,LOGINDO STOUT,1951,67.80,Ya,Seharusnya Pandu karena GT>=500

In [ ]:
import pandas as pd

# Memeriksa baris duplikat pada dataframe combined_spbspog_dermaga_SPK
num_duplicates = combined_spbspog_dermaga_SPK.duplicated().sum()

print(f"Analisis Duplikat untuk combined_spbspog_dermaga_SPK:")
print(f"Total baris: {len(combined_spbspog_dermaga_SPK)}")
print(f"Jumlah baris duplikat: {num_duplicates}")

if num_duplicates > 0:
    print("\nPreview baris duplikat:")
    display(combined_spbspog_dermaga_SPK[combined_spbspog_dermaga_SPK.duplicated(keep=False)].sort_values(by='No Layanan').head(10))
else:
    print("\nTidak ada baris duplikat yang ditemukan.")

Analisis Duplikat untuk combined_spbspog_dermaga_SPK:
Total baris: 3241
Jumlah baris duplikat: 0

Tidak ada baris duplikat yang ditemukan.

In [ ]:
import pandas as pd

# Memeriksa baris duplikat pada dataframe combined_spbspog_dermaga_NoSPK
num_duplicates = combined_spbspog_dermaga_NoSPK.duplicated().sum()

print(f"Analisis Duplikat untuk combined_spbspog_dermaga_SPK:")
print(f"Total baris: {len(combined_spbspog_dermaga_NoSPK)}")
print(f"Jumlah baris duplikat: {num_duplicates}")

if num_duplicates > 0:
    print("\nPreview baris duplikat:")
    display(combined_spbspog_dermaga_NoSPK[combined_spbspog_dermaga_NoSPK.duplicated(keep=False)].sort_values(by='No Layanan').head(10))
else:
    print("\nTidak ada baris duplikat yang ditemukan.")

Analisis Duplikat untuk combined_spbspog_dermaga_SPK:
Total baris: 329
Jumlah baris duplikat: 0

Tidak ada baris duplikat yang ditemukan.

In [ ]:
# 1. Kondisi GT >= 500 dan LOA >= 70 (Pandu & Tunda)
df_noSPK_GT500_LOA70 = combined_spbspog_dermaga_NoSPK[
    (combined_spbspog_dermaga_NoSPK['GT'] >= 500) & (combined_spbspog_dermaga_NoSPK['LOA'] >= 70)
].copy()

# 2. Kondisi GT >= 500 tapi LOA < 70 (Pandu Saja)
df_noSPK_GT500_only = combined_spbspog_dermaga_NoSPK[
    (combined_spbspog_dermaga_NoSPK['GT'] >= 500) & (combined_spbspog_dermaga_NoSPK['LOA'] < 70)
].copy()

# 3. Kondisi selain 1 dan 2 (GT < 500)
# FIX: Menambahkan kurung tutup/buka yang benar agar operator '|' tidak memproses angka secara langsung
df_noSPK_Lainnya = combined_spbspog_dermaga_NoSPK[
    (combined_spbspog_dermaga_NoSPK['GT'] < 500) | (combined_spbspog_dermaga_NoSPK['LOA'] < 70)
].copy()

# Verifikasi jumlah baris
print(f"Total Data NoSPK: {len(combined_spbspog_dermaga_NoSPK)}")
print(f"1) GT >= 500 & LOA >= 70: {len(df_noSPK_GT500_LOA70)} baris")
print(f"2) GT >= 500 & LOA < 70: {len(df_noSPK_GT500_only)} baris")
print(f"3) Lainnya (GT < 500 atau LOA < 70): {len(df_noSPK_Lainnya)} baris")

Total Data NoSPK: 329
1) GT >= 500 & LOA >= 70: 30 baris
2) GT >= 500 & LOA < 70: 5 baris
3) Lainnya (GT < 500 atau LOA < 70): 299 baris

In [ ]:
def export_dataframe_by_name():
    """
    Meminta input nama variabel dataframe dari user,
    lalu mengekspornya ke Excel.
    """
    df_name = input("Masukkan nama variabel dataframe yang ingin diekspor (contoh: combined_spbspog_dermaga): ").strip()

    # Memeriksa apakah variabel ada di namespace global
    if df_name in globals():
        df = globals()[df_name]

        if isinstance(df, pd.DataFrame):
            filename = f"{df_name}.xlsx"
            df.to_excel(filename, index=False)
            files.download(filename)
            print(f"Berhasil! Dataframe '{df_name}' sedang diunduh sebagai '{filename}'.")
        else:
            print(f"Error: '{df_name}' bukan merupakan Pandas DataFrame.")
    else:
        print(f"Error: Variabel '{df_name}' tidak ditemukan.")

# Jalankan fungsi
export_dataframe_by_name()

Masukkan nama variabel dataframe yang ingin diekspor (contoh: combined_spbspog_dermaga): df_noSPK_GT500_only

Berhasil! Dataframe 'df_noSPK_GT500_only' sedang diunduh sebagai 'df_noSPK_GT500_only.xlsx'.